packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@firebase/util': true
  '@prisma/client': true
  '@prisma/engines': true
  cpu-features: true
  fastify-socket.io: true
  msgpackr-extract: true
  prisma: true
  protobufjs: true
  ssh2: true
  unrs-resolver: true
