global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mosa-backend'
    static_configs:
      - targets: ['backend:8080']
    metrics_path: '/metrics'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'mosquitto'
    static_configs:
      - targets: ['mosquitto-exporter:9234']
