apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: mosa-postgres:5432
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    database: ${POSTGRES_DB}
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1600
      timescaledb: true
